# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: publish code on npm

on:
  push:
    branches:
      - main
      - dev
  repository_dispatch:
    types:
      - webhook

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        node-version: ["20.x"]

    steps:
      - uses: actions/checkout@v4
      - name: Check if version has changed
        id: check_version
        run: |
          if git diff HEAD^ HEAD package.json | grep '"version"'; then
            echo "::set-output name=version_changed::true";
          else
            echo "::set-output name=version_changed::false";
          fi
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"

      - name: Npm Build
        if: steps.check_version.outputs.version_changed == 'true'
        run: |
          npm ci
          npm run build
      - name: Publish to npm
        if: steps.check_version.outputs.version_changed == 'true'
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
